services:
  db:
    container_name: "db"
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=gostok
      - POSTGRES_PASSWORD=goStok[@o
      - POSTGRES_DB=fastapi_practice
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge